default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flash_cash_development

test:
  <<: *default
  database: flash_cash_test

production:
  <<: *default
  database: flash_cash_production
